# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-19 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20190619_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(default=datetime.datetime(2019, 6, 19, 13, 32, 48, 757185, tzinfo=utc), upload_to='image/'),
            preserve_default=False,
        ),
    ]
